// source: account.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var model_pb = require('./model_pb.js');
goog.object.extend(proto, model_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.compservice.model.protobuf.Account', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.AccountServiceRequest', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.AccountServiceRequest.PayloadCase', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.AccountServiceResponse', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.AccountServiceResponse.PayloadCase', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.AddAccountRequestPayload', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.AuthenticateRequestPayload', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.GetAccountResponsePayload', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.UpdateAccountRequestPayload', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.AccountServiceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.compservice.model.protobuf.AccountServiceRequest.oneofGroups_);
};
goog.inherits(proto.compservice.model.protobuf.AccountServiceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.AccountServiceRequest.displayName = 'proto.compservice.model.protobuf.AccountServiceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.AccountServiceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, 500, null, proto.compservice.model.protobuf.AccountServiceResponse.oneofGroups_);
};
goog.inherits(proto.compservice.model.protobuf.AccountServiceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.AccountServiceResponse.displayName = 'proto.compservice.model.protobuf.AccountServiceResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.Account = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.compservice.model.protobuf.Account, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.Account.displayName = 'proto.compservice.model.protobuf.Account';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.AddAccountRequestPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.compservice.model.protobuf.AddAccountRequestPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.AddAccountRequestPayload.displayName = 'proto.compservice.model.protobuf.AddAccountRequestPayload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.compservice.model.protobuf.AuthenticateRequestPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.AuthenticateRequestPayload.displayName = 'proto.compservice.model.protobuf.AuthenticateRequestPayload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.displayName = 'proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.GetAccountResponsePayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.compservice.model.protobuf.GetAccountResponsePayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.GetAccountResponsePayload.displayName = 'proto.compservice.model.protobuf.GetAccountResponsePayload';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.UpdateAccountRequestPayload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.compservice.model.protobuf.UpdateAccountRequestPayload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.UpdateAccountRequestPayload.displayName = 'proto.compservice.model.protobuf.UpdateAccountRequestPayload';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.compservice.model.protobuf.AccountServiceRequest.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.compservice.model.protobuf.AccountServiceRequest.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  ADDACCOUNT: 1,
  UPDATEACCOUNT: 2,
  UPDATEPROFILEPICTUREREQUESTPAYLOAD: 3
};

/**
 * @return {proto.compservice.model.protobuf.AccountServiceRequest.PayloadCase}
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.getPayloadCase = function() {
  return /** @type {proto.compservice.model.protobuf.AccountServiceRequest.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.compservice.model.protobuf.AccountServiceRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.AccountServiceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.AccountServiceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.AccountServiceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    addaccount: (f = msg.getAddaccount()) && proto.compservice.model.protobuf.AddAccountRequestPayload.toObject(includeInstance, f),
    updateaccount: (f = msg.getUpdateaccount()) && proto.compservice.model.protobuf.UpdateAccountRequestPayload.toObject(includeInstance, f),
    updateprofilepicturerequestpayload: (f = msg.getUpdateprofilepicturerequestpayload()) && proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.AccountServiceRequest}
 */
proto.compservice.model.protobuf.AccountServiceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.AccountServiceRequest;
  return proto.compservice.model.protobuf.AccountServiceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.AccountServiceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.AccountServiceRequest}
 */
proto.compservice.model.protobuf.AccountServiceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.compservice.model.protobuf.AddAccountRequestPayload;
      reader.readMessage(value,proto.compservice.model.protobuf.AddAccountRequestPayload.deserializeBinaryFromReader);
      msg.setAddaccount(value);
      break;
    case 2:
      var value = new proto.compservice.model.protobuf.UpdateAccountRequestPayload;
      reader.readMessage(value,proto.compservice.model.protobuf.UpdateAccountRequestPayload.deserializeBinaryFromReader);
      msg.setUpdateaccount(value);
      break;
    case 3:
      var value = new proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload;
      reader.readMessage(value,proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.deserializeBinaryFromReader);
      msg.setUpdateprofilepicturerequestpayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.AccountServiceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.AccountServiceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.AccountServiceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddaccount();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.compservice.model.protobuf.AddAccountRequestPayload.serializeBinaryToWriter
    );
  }
  f = message.getUpdateaccount();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.compservice.model.protobuf.UpdateAccountRequestPayload.serializeBinaryToWriter
    );
  }
  f = message.getUpdateprofilepicturerequestpayload();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.serializeBinaryToWriter
    );
  }
};


/**
 * optional AddAccountRequestPayload addAccount = 1;
 * @return {?proto.compservice.model.protobuf.AddAccountRequestPayload}
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.getAddaccount = function() {
  return /** @type{?proto.compservice.model.protobuf.AddAccountRequestPayload} */ (
    jspb.Message.getWrapperField(this, proto.compservice.model.protobuf.AddAccountRequestPayload, 1));
};


/**
 * @param {?proto.compservice.model.protobuf.AddAccountRequestPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.AccountServiceRequest} returns this
*/
proto.compservice.model.protobuf.AccountServiceRequest.prototype.setAddaccount = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.compservice.model.protobuf.AccountServiceRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.AccountServiceRequest} returns this
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.clearAddaccount = function() {
  return this.setAddaccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.hasAddaccount = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional UpdateAccountRequestPayload updateAccount = 2;
 * @return {?proto.compservice.model.protobuf.UpdateAccountRequestPayload}
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.getUpdateaccount = function() {
  return /** @type{?proto.compservice.model.protobuf.UpdateAccountRequestPayload} */ (
    jspb.Message.getWrapperField(this, proto.compservice.model.protobuf.UpdateAccountRequestPayload, 2));
};


/**
 * @param {?proto.compservice.model.protobuf.UpdateAccountRequestPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.AccountServiceRequest} returns this
*/
proto.compservice.model.protobuf.AccountServiceRequest.prototype.setUpdateaccount = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.compservice.model.protobuf.AccountServiceRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.AccountServiceRequest} returns this
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.clearUpdateaccount = function() {
  return this.setUpdateaccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.hasUpdateaccount = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional UpdateProfilePictureRequestPayload updateProfilePictureRequestPayload = 3;
 * @return {?proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload}
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.getUpdateprofilepicturerequestpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload} */ (
    jspb.Message.getWrapperField(this, proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload, 3));
};


/**
 * @param {?proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.AccountServiceRequest} returns this
*/
proto.compservice.model.protobuf.AccountServiceRequest.prototype.setUpdateprofilepicturerequestpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.compservice.model.protobuf.AccountServiceRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.AccountServiceRequest} returns this
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.clearUpdateprofilepicturerequestpayload = function() {
  return this.setUpdateprofilepicturerequestpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.AccountServiceRequest.prototype.hasUpdateprofilepicturerequestpayload = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.compservice.model.protobuf.AccountServiceResponse.oneofGroups_ = [[1,4,100000]];

/**
 * @enum {number}
 */
proto.compservice.model.protobuf.AccountServiceResponse.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  GETACCOUNTRESPONSEPAYLOAD: 1,
  AUTHENTICATIONRESPONSEPAYLOAD: 4,
  ERRORRESPONSE: 100000
};

/**
 * @return {proto.compservice.model.protobuf.AccountServiceResponse.PayloadCase}
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.getPayloadCase = function() {
  return /** @type {proto.compservice.model.protobuf.AccountServiceResponse.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.compservice.model.protobuf.AccountServiceResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.AccountServiceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.AccountServiceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.AccountServiceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    getaccountresponsepayload: (f = msg.getGetaccountresponsepayload()) && proto.compservice.model.protobuf.GetAccountResponsePayload.toObject(includeInstance, f),
    authenticationresponsepayload: (f = msg.getAuthenticationresponsepayload()) && model_pb.AuthenticationResponsePayload.toObject(includeInstance, f),
    errorresponse: (f = msg.getErrorresponse()) && model_pb.ErrorResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.AccountServiceResponse}
 */
proto.compservice.model.protobuf.AccountServiceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.AccountServiceResponse;
  return proto.compservice.model.protobuf.AccountServiceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.AccountServiceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.AccountServiceResponse}
 */
proto.compservice.model.protobuf.AccountServiceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.compservice.model.protobuf.GetAccountResponsePayload;
      reader.readMessage(value,proto.compservice.model.protobuf.GetAccountResponsePayload.deserializeBinaryFromReader);
      msg.setGetaccountresponsepayload(value);
      break;
    case 4:
      var value = new model_pb.AuthenticationResponsePayload;
      reader.readMessage(value,model_pb.AuthenticationResponsePayload.deserializeBinaryFromReader);
      msg.setAuthenticationresponsepayload(value);
      break;
    case 100000:
      var value = new model_pb.ErrorResponse;
      reader.readMessage(value,model_pb.ErrorResponse.deserializeBinaryFromReader);
      msg.setErrorresponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.AccountServiceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.AccountServiceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.AccountServiceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGetaccountresponsepayload();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.compservice.model.protobuf.GetAccountResponsePayload.serializeBinaryToWriter
    );
  }
  f = message.getAuthenticationresponsepayload();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      model_pb.AuthenticationResponsePayload.serializeBinaryToWriter
    );
  }
  f = message.getErrorresponse();
  if (f != null) {
    writer.writeMessage(
      100000,
      f,
      model_pb.ErrorResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional GetAccountResponsePayload getAccountResponsePayload = 1;
 * @return {?proto.compservice.model.protobuf.GetAccountResponsePayload}
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.getGetaccountresponsepayload = function() {
  return /** @type{?proto.compservice.model.protobuf.GetAccountResponsePayload} */ (
    jspb.Message.getWrapperField(this, proto.compservice.model.protobuf.GetAccountResponsePayload, 1));
};


/**
 * @param {?proto.compservice.model.protobuf.GetAccountResponsePayload|undefined} value
 * @return {!proto.compservice.model.protobuf.AccountServiceResponse} returns this
*/
proto.compservice.model.protobuf.AccountServiceResponse.prototype.setGetaccountresponsepayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.compservice.model.protobuf.AccountServiceResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.AccountServiceResponse} returns this
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.clearGetaccountresponsepayload = function() {
  return this.setGetaccountresponsepayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.hasGetaccountresponsepayload = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional AuthenticationResponsePayload authenticationResponsePayload = 4;
 * @return {?proto.compservice.model.protobuf.AuthenticationResponsePayload}
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.getAuthenticationresponsepayload = function() {
  return /** @type{?proto.compservice.model.protobuf.AuthenticationResponsePayload} */ (
    jspb.Message.getWrapperField(this, model_pb.AuthenticationResponsePayload, 4));
};


/**
 * @param {?proto.compservice.model.protobuf.AuthenticationResponsePayload|undefined} value
 * @return {!proto.compservice.model.protobuf.AccountServiceResponse} returns this
*/
proto.compservice.model.protobuf.AccountServiceResponse.prototype.setAuthenticationresponsepayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.compservice.model.protobuf.AccountServiceResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.AccountServiceResponse} returns this
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.clearAuthenticationresponsepayload = function() {
  return this.setAuthenticationresponsepayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.hasAuthenticationresponsepayload = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ErrorResponse errorResponse = 100000;
 * @return {?proto.compservice.model.protobuf.ErrorResponse}
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.getErrorresponse = function() {
  return /** @type{?proto.compservice.model.protobuf.ErrorResponse} */ (
    jspb.Message.getWrapperField(this, model_pb.ErrorResponse, 100000));
};


/**
 * @param {?proto.compservice.model.protobuf.ErrorResponse|undefined} value
 * @return {!proto.compservice.model.protobuf.AccountServiceResponse} returns this
*/
proto.compservice.model.protobuf.AccountServiceResponse.prototype.setErrorresponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 100000, proto.compservice.model.protobuf.AccountServiceResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.AccountServiceResponse} returns this
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.clearErrorresponse = function() {
  return this.setErrorresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.AccountServiceResponse.prototype.hasErrorresponse = function() {
  return jspb.Message.getField(this, 100000) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.Account.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.Account.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.Account} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.Account.toObject = function(includeInstance, msg) {
  var f, obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    firstname: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lastname: jspb.Message.getFieldWithDefault(msg, 3, ""),
    email: jspb.Message.getFieldWithDefault(msg, 4, ""),
    birthdate: (f = msg.getBirthdate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    password: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.Account}
 */
proto.compservice.model.protobuf.Account.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.Account;
  return proto.compservice.model.protobuf.Account.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.Account} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.Account}
 */
proto.compservice.model.protobuf.Account.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirstname(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastname(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setBirthdate(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.Account.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.Account.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.Account} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.Account.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFirstname();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLastname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBirthdate();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string userId = 1;
 * @return {string}
 */
proto.compservice.model.protobuf.Account.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.Account} returns this
 */
proto.compservice.model.protobuf.Account.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string firstName = 2;
 * @return {string}
 */
proto.compservice.model.protobuf.Account.prototype.getFirstname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.Account} returns this
 */
proto.compservice.model.protobuf.Account.prototype.setFirstname = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string lastName = 3;
 * @return {string}
 */
proto.compservice.model.protobuf.Account.prototype.getLastname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.Account} returns this
 */
proto.compservice.model.protobuf.Account.prototype.setLastname = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string email = 4;
 * @return {string}
 */
proto.compservice.model.protobuf.Account.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.Account} returns this
 */
proto.compservice.model.protobuf.Account.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp birthDate = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.compservice.model.protobuf.Account.prototype.getBirthdate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.compservice.model.protobuf.Account} returns this
*/
proto.compservice.model.protobuf.Account.prototype.setBirthdate = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.Account} returns this
 */
proto.compservice.model.protobuf.Account.prototype.clearBirthdate = function() {
  return this.setBirthdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.Account.prototype.hasBirthdate = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string password = 6;
 * @return {string}
 */
proto.compservice.model.protobuf.Account.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.Account} returns this
 */
proto.compservice.model.protobuf.Account.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.AddAccountRequestPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.AddAccountRequestPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    firstname: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lastname: jspb.Message.getFieldWithDefault(msg, 3, ""),
    email: jspb.Message.getFieldWithDefault(msg, 4, ""),
    birthdate: (f = msg.getBirthdate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.AddAccountRequestPayload}
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.AddAccountRequestPayload;
  return proto.compservice.model.protobuf.AddAccountRequestPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.AddAccountRequestPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.AddAccountRequestPayload}
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirstname(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastname(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setBirthdate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.AddAccountRequestPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.AddAccountRequestPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFirstname();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLastname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBirthdate();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string firstName = 2;
 * @return {string}
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.getFirstname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.AddAccountRequestPayload} returns this
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.setFirstname = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string lastName = 3;
 * @return {string}
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.getLastname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.AddAccountRequestPayload} returns this
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.setLastname = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string email = 4;
 * @return {string}
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.AddAccountRequestPayload} returns this
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp birthDate = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.getBirthdate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.compservice.model.protobuf.AddAccountRequestPayload} returns this
*/
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.setBirthdate = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.AddAccountRequestPayload} returns this
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.clearBirthdate = function() {
  return this.setBirthdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.AddAccountRequestPayload.prototype.hasBirthdate = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.AuthenticateRequestPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.AuthenticateRequestPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    username: jspb.Message.getFieldWithDefault(msg, 2, ""),
    password: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.AuthenticateRequestPayload}
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.AuthenticateRequestPayload;
  return proto.compservice.model.protobuf.AuthenticateRequestPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.AuthenticateRequestPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.AuthenticateRequestPayload}
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.AuthenticateRequestPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.AuthenticateRequestPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string username = 2;
 * @return {string}
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.AuthenticateRequestPayload} returns this
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string password = 3;
 * @return {string}
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.AuthenticateRequestPayload} returns this
 */
proto.compservice.model.protobuf.AuthenticateRequestPayload.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    picture: msg.getPicture_asB64(),
    userid: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload}
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload;
  return proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload}
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPicture(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPicture_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bytes picture = 1;
 * @return {!(string|Uint8Array)}
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.prototype.getPicture = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes picture = 1;
 * This is a type-conversion wrapper around `getPicture()`
 * @return {string}
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.prototype.getPicture_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPicture()));
};


/**
 * optional bytes picture = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPicture()`
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.prototype.getPicture_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPicture()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload} returns this
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.prototype.setPicture = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional string userId = 2;
 * @return {string}
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload} returns this
 */
proto.compservice.model.protobuf.UpdateProfilePictureRequestPayload.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.GetAccountResponsePayload.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.GetAccountResponsePayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.GetAccountResponsePayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.GetAccountResponsePayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    account: (f = msg.getAccount()) && proto.compservice.model.protobuf.Account.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.GetAccountResponsePayload}
 */
proto.compservice.model.protobuf.GetAccountResponsePayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.GetAccountResponsePayload;
  return proto.compservice.model.protobuf.GetAccountResponsePayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.GetAccountResponsePayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.GetAccountResponsePayload}
 */
proto.compservice.model.protobuf.GetAccountResponsePayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.compservice.model.protobuf.Account;
      reader.readMessage(value,proto.compservice.model.protobuf.Account.deserializeBinaryFromReader);
      msg.setAccount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.GetAccountResponsePayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.GetAccountResponsePayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.GetAccountResponsePayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.GetAccountResponsePayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccount();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.compservice.model.protobuf.Account.serializeBinaryToWriter
    );
  }
};


/**
 * optional Account account = 1;
 * @return {?proto.compservice.model.protobuf.Account}
 */
proto.compservice.model.protobuf.GetAccountResponsePayload.prototype.getAccount = function() {
  return /** @type{?proto.compservice.model.protobuf.Account} */ (
    jspb.Message.getWrapperField(this, proto.compservice.model.protobuf.Account, 1));
};


/**
 * @param {?proto.compservice.model.protobuf.Account|undefined} value
 * @return {!proto.compservice.model.protobuf.GetAccountResponsePayload} returns this
*/
proto.compservice.model.protobuf.GetAccountResponsePayload.prototype.setAccount = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.GetAccountResponsePayload} returns this
 */
proto.compservice.model.protobuf.GetAccountResponsePayload.prototype.clearAccount = function() {
  return this.setAccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.GetAccountResponsePayload.prototype.hasAccount = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.UpdateAccountRequestPayload.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.UpdateAccountRequestPayload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.UpdateAccountRequestPayload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.UpdateAccountRequestPayload.toObject = function(includeInstance, msg) {
  var f, obj = {
    account: (f = msg.getAccount()) && proto.compservice.model.protobuf.Account.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.UpdateAccountRequestPayload}
 */
proto.compservice.model.protobuf.UpdateAccountRequestPayload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.UpdateAccountRequestPayload;
  return proto.compservice.model.protobuf.UpdateAccountRequestPayload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.UpdateAccountRequestPayload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.UpdateAccountRequestPayload}
 */
proto.compservice.model.protobuf.UpdateAccountRequestPayload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.compservice.model.protobuf.Account;
      reader.readMessage(value,proto.compservice.model.protobuf.Account.deserializeBinaryFromReader);
      msg.setAccount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.UpdateAccountRequestPayload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.UpdateAccountRequestPayload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.UpdateAccountRequestPayload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.UpdateAccountRequestPayload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccount();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.compservice.model.protobuf.Account.serializeBinaryToWriter
    );
  }
};


/**
 * optional Account account = 1;
 * @return {?proto.compservice.model.protobuf.Account}
 */
proto.compservice.model.protobuf.UpdateAccountRequestPayload.prototype.getAccount = function() {
  return /** @type{?proto.compservice.model.protobuf.Account} */ (
    jspb.Message.getWrapperField(this, proto.compservice.model.protobuf.Account, 1));
};


/**
 * @param {?proto.compservice.model.protobuf.Account|undefined} value
 * @return {!proto.compservice.model.protobuf.UpdateAccountRequestPayload} returns this
*/
proto.compservice.model.protobuf.UpdateAccountRequestPayload.prototype.setAccount = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.UpdateAccountRequestPayload} returns this
 */
proto.compservice.model.protobuf.UpdateAccountRequestPayload.prototype.clearAccount = function() {
  return this.setAccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.UpdateAccountRequestPayload.prototype.hasAccount = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.compservice.model.protobuf);
