// source: callback.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var event_pb = require('./event_pb.js');
goog.object.extend(proto, event_pb);
var command_pb = require('./command_pb.js');
goog.object.extend(proto, command_pb);
var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
goog.exportSymbol('proto.compservice.model.protobuf.CommandCallback', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.CommandExecutionResult', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.ErrorCallback', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.CommandCallback = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.compservice.model.protobuf.CommandCallback.repeatedFields_, null);
};
goog.inherits(proto.compservice.model.protobuf.CommandCallback, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.CommandCallback.displayName = 'proto.compservice.model.protobuf.CommandCallback';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.ErrorCallback = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.compservice.model.protobuf.ErrorCallback, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.ErrorCallback.displayName = 'proto.compservice.model.protobuf.ErrorCallback';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.compservice.model.protobuf.CommandCallback.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.CommandCallback.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.CommandCallback} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.CommandCallback.toObject = function(includeInstance, msg) {
  var f, obj = {
    correlationid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    result: jspb.Message.getFieldWithDefault(msg, 3, 0),
    errorinfo: (f = msg.getErrorinfo()) && proto.compservice.model.protobuf.ErrorCallback.toObject(includeInstance, f),
    eventsList: jspb.Message.toObjectList(msg.getEventsList(),
    event_pb.Event.toObject, includeInstance),
    command: (f = msg.getCommand()) && command_pb.Command.toObject(includeInstance, f),
    numberofevents: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.CommandCallback}
 */
proto.compservice.model.protobuf.CommandCallback.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.CommandCallback;
  return proto.compservice.model.protobuf.CommandCallback.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.CommandCallback} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.CommandCallback}
 */
proto.compservice.model.protobuf.CommandCallback.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCorrelationid(value);
      break;
    case 3:
      var value = /** @type {!proto.compservice.model.protobuf.CommandExecutionResult} */ (reader.readEnum());
      msg.setResult(value);
      break;
    case 4:
      var value = new proto.compservice.model.protobuf.ErrorCallback;
      reader.readMessage(value,proto.compservice.model.protobuf.ErrorCallback.deserializeBinaryFromReader);
      msg.setErrorinfo(value);
      break;
    case 5:
      var value = new event_pb.Event;
      reader.readMessage(value,event_pb.Event.deserializeBinaryFromReader);
      msg.addEvents(value);
      break;
    case 6:
      var value = new command_pb.Command;
      reader.readMessage(value,command_pb.Command.deserializeBinaryFromReader);
      msg.setCommand(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumberofevents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.CommandCallback.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.CommandCallback} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.CommandCallback.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCorrelationid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getResult();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getErrorinfo();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.compservice.model.protobuf.ErrorCallback.serializeBinaryToWriter
    );
  }
  f = message.getEventsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      event_pb.Event.serializeBinaryToWriter
    );
  }
  f = message.getCommand();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      command_pb.Command.serializeBinaryToWriter
    );
  }
  f = message.getNumberofevents();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
};


/**
 * optional string correlationId = 2;
 * @return {string}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.getCorrelationid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.CommandCallback} returns this
 */
proto.compservice.model.protobuf.CommandCallback.prototype.setCorrelationid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional CommandExecutionResult result = 3;
 * @return {!proto.compservice.model.protobuf.CommandExecutionResult}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.getResult = function() {
  return /** @type {!proto.compservice.model.protobuf.CommandExecutionResult} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.compservice.model.protobuf.CommandExecutionResult} value
 * @return {!proto.compservice.model.protobuf.CommandCallback} returns this
 */
proto.compservice.model.protobuf.CommandCallback.prototype.setResult = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional ErrorCallback errorInfo = 4;
 * @return {?proto.compservice.model.protobuf.ErrorCallback}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.getErrorinfo = function() {
  return /** @type{?proto.compservice.model.protobuf.ErrorCallback} */ (
    jspb.Message.getWrapperField(this, proto.compservice.model.protobuf.ErrorCallback, 4));
};


/**
 * @param {?proto.compservice.model.protobuf.ErrorCallback|undefined} value
 * @return {!proto.compservice.model.protobuf.CommandCallback} returns this
*/
proto.compservice.model.protobuf.CommandCallback.prototype.setErrorinfo = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.CommandCallback} returns this
 */
proto.compservice.model.protobuf.CommandCallback.prototype.clearErrorinfo = function() {
  return this.setErrorinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.hasErrorinfo = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated Event events = 5;
 * @return {!Array<!proto.compservice.model.protobuf.Event>}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.getEventsList = function() {
  return /** @type{!Array<!proto.compservice.model.protobuf.Event>} */ (
    jspb.Message.getRepeatedWrapperField(this, event_pb.Event, 5));
};


/**
 * @param {!Array<!proto.compservice.model.protobuf.Event>} value
 * @return {!proto.compservice.model.protobuf.CommandCallback} returns this
*/
proto.compservice.model.protobuf.CommandCallback.prototype.setEventsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.compservice.model.protobuf.Event=} opt_value
 * @param {number=} opt_index
 * @return {!proto.compservice.model.protobuf.Event}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.addEvents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.compservice.model.protobuf.Event, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.compservice.model.protobuf.CommandCallback} returns this
 */
proto.compservice.model.protobuf.CommandCallback.prototype.clearEventsList = function() {
  return this.setEventsList([]);
};


/**
 * optional Command command = 6;
 * @return {?proto.compservice.model.protobuf.Command}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.getCommand = function() {
  return /** @type{?proto.compservice.model.protobuf.Command} */ (
    jspb.Message.getWrapperField(this, command_pb.Command, 6));
};


/**
 * @param {?proto.compservice.model.protobuf.Command|undefined} value
 * @return {!proto.compservice.model.protobuf.CommandCallback} returns this
*/
proto.compservice.model.protobuf.CommandCallback.prototype.setCommand = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.CommandCallback} returns this
 */
proto.compservice.model.protobuf.CommandCallback.prototype.clearCommand = function() {
  return this.setCommand(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.hasCommand = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int32 numberOfEvents = 7;
 * @return {number}
 */
proto.compservice.model.protobuf.CommandCallback.prototype.getNumberofevents = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.compservice.model.protobuf.CommandCallback} returns this
 */
proto.compservice.model.protobuf.CommandCallback.prototype.setNumberofevents = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.ErrorCallback.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.ErrorCallback.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.ErrorCallback} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.ErrorCallback.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, ""),
    payload: (f = msg.getPayload()) && google_protobuf_any_pb.Any.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.ErrorCallback}
 */
proto.compservice.model.protobuf.ErrorCallback.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.ErrorCallback;
  return proto.compservice.model.protobuf.ErrorCallback.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.ErrorCallback} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.ErrorCallback}
 */
proto.compservice.model.protobuf.ErrorCallback.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.ErrorCallback.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.ErrorCallback.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.ErrorCallback} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.ErrorCallback.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.compservice.model.protobuf.ErrorCallback.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.ErrorCallback} returns this
 */
proto.compservice.model.protobuf.ErrorCallback.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Any payload = 2;
 * @return {?proto.google.protobuf.Any}
 */
proto.compservice.model.protobuf.ErrorCallback.prototype.getPayload = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 2));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.compservice.model.protobuf.ErrorCallback} returns this
*/
proto.compservice.model.protobuf.ErrorCallback.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.ErrorCallback} returns this
 */
proto.compservice.model.protobuf.ErrorCallback.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.ErrorCallback.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * @enum {number}
 */
proto.compservice.model.protobuf.CommandExecutionResult = {
  COMMAND_EXECUTION_RESULT_SUCCESS: 0,
  COMMAND_EXECUTION_RESULT_FAIL: 1,
  COMMAND_EXECUTION_RESULT_TIMEOUT: 2
};

goog.object.extend(exports, proto.compservice.model.protobuf);
