// source: common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var eventpayload_pb = require('./eventpayload_pb.js');
goog.object.extend(proto, eventpayload_pb);
var commandpayload_pb = require('./commandpayload_pb.js');
goog.object.extend(proto, commandpayload_pb);
goog.exportSymbol('proto.compservice.model.protobuf.MessageInfo', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.MessageInfo.PayloadCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.MessageInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.compservice.model.protobuf.MessageInfo.oneofGroups_);
};
goog.inherits(proto.compservice.model.protobuf.MessageInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.MessageInfo.displayName = 'proto.compservice.model.protobuf.MessageInfo';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.compservice.model.protobuf.MessageInfo.oneofGroups_ = [[11,12,13,17,18,19,110,111,112,115,116,117,118,119,120,122,123,124,125,126,127,128,129,21,22,23,24,25,26,27,28,29,210,211,212,213,214,215,219,222,223,224]];

/**
 * @enum {number}
 */
proto.compservice.model.protobuf.MessageInfo.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  ADDACADEMYPAYLOAD: 11,
  ADDCATEGORYPAYLOAD: 12,
  ADDCOMPETITORPAYLOAD: 13,
  CATEGORYREGISTRATIONSTATUSCHANGEPAYLOAD: 17,
  CHANGECOMPETITORCATEGORYPAYLOAD: 18,
  CHANGEFIGHTORDERPAYLOAD: 19,
  COMPETITORCATEGORYADDEDPAYLOAD: 110,
  CREATECOMPETITIONPAYLOAD: 111,
  CREATEFAKECOMPETITORSPAYLOAD: 112,
  FIGHTEDITORAPPLYCHANGESPAYLOAD: 115,
  GENERATEABSOLUTECATEGORYPAYLOAD: 116,
  GENERATEBRACKETSPAYLOAD: 117,
  GENERATECATEGORIESFROMRESTRICTIONSPAYLOAD: 118,
  GENERATESCHEDULEPAYLOAD: 119,
  PROPAGATECOMPETITORSPAYLOAD: 120,
  REMOVEACADEMYPAYLOAD: 122,
  REMOVECOMPETITORPAYLOAD: 123,
  SETFIGHTRESULTPAYLOAD: 124,
  UPDATEACADEMYPAYLOAD: 125,
  UPDATECOMPETIONPROPERTIESPAYLOAD: 126,
  UPDATECOMPETITORPAYLOAD: 127,
  UPDATEREGISTRATIONINFOPAYLOAD: 128,
  UPDATESTAGESTATUSPAYLOAD: 129,
  BRACKETSGENERATEDPAYLOAD: 21,
  CATEGORYADDEDPAYLOAD: 22,
  COMPETITIONCREATEDPAYLOAD: 23,
  COMPETITIONINFOPAYLOAD: 24,
  COMPETITIONPROPERTIESUPDATEDPAYLOAD: 25,
  COMPETITIONSTATUSUPDATEDPAYLOAD: 26,
  COMPETITORADDEDPAYLOAD: 27,
  COMPETITORREMOVEDPAYLOAD: 28,
  COMPETITORSPROPAGATEDTOSTAGEPAYLOAD: 29,
  COMPETITORUPDATEDPAYLOAD: 210,
  FIGHTCOMPETITORSASSIGNEDPAYLOAD: 211,
  FIGHTEDITORCHANGESAPPLIEDPAYLOAD: 212,
  FIGHTSADDEDTOSTAGEPAYLOAD: 213,
  FIGHTSTARTTIMEUPDATEDPAYLOAD: 214,
  MATSUPDATEDPAYLOAD: 215,
  REGISTRATIONINFOUPDATEDPAYLOAD: 219,
  SCHEDULEGENERATEDPAYLOAD: 222,
  STAGERESULTSETPAYLOAD: 223,
  STAGESTATUSUPDATEDPAYLOAD: 224
};

/**
 * @return {proto.compservice.model.protobuf.MessageInfo.PayloadCase}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getPayloadCase = function() {
  return /** @type {proto.compservice.model.protobuf.MessageInfo.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.MessageInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.MessageInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.MessageInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    correlationid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    competitionid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    competitorid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    categoryid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    matid: jspb.Message.getFieldWithDefault(msg, 6, ""),
    addacademypayload: (f = msg.getAddacademypayload()) && commandpayload_pb.AddAcademyPayload.toObject(includeInstance, f),
    addcategorypayload: (f = msg.getAddcategorypayload()) && commandpayload_pb.AddCategoryPayload.toObject(includeInstance, f),
    addcompetitorpayload: (f = msg.getAddcompetitorpayload()) && commandpayload_pb.AddCompetitorPayload.toObject(includeInstance, f),
    categoryregistrationstatuschangepayload: (f = msg.getCategoryregistrationstatuschangepayload()) && commandpayload_pb.CategoryRegistrationStatusChangePayload.toObject(includeInstance, f),
    changecompetitorcategorypayload: (f = msg.getChangecompetitorcategorypayload()) && commandpayload_pb.ChangeCompetitorCategoryPayload.toObject(includeInstance, f),
    changefightorderpayload: (f = msg.getChangefightorderpayload()) && commandpayload_pb.ChangeFightOrderPayload.toObject(includeInstance, f),
    competitorcategoryaddedpayload: (f = msg.getCompetitorcategoryaddedpayload()) && commandpayload_pb.CompetitorCategoryAddedPayload.toObject(includeInstance, f),
    createcompetitionpayload: (f = msg.getCreatecompetitionpayload()) && commandpayload_pb.CreateCompetitionPayload.toObject(includeInstance, f),
    createfakecompetitorspayload: (f = msg.getCreatefakecompetitorspayload()) && commandpayload_pb.CreateFakeCompetitorsPayload.toObject(includeInstance, f),
    fighteditorapplychangespayload: (f = msg.getFighteditorapplychangespayload()) && commandpayload_pb.FightEditorApplyChangesPayload.toObject(includeInstance, f),
    generateabsolutecategorypayload: (f = msg.getGenerateabsolutecategorypayload()) && commandpayload_pb.GenerateAbsoluteCategoryPayload.toObject(includeInstance, f),
    generatebracketspayload: (f = msg.getGeneratebracketspayload()) && commandpayload_pb.GenerateBracketsPayload.toObject(includeInstance, f),
    generatecategoriesfromrestrictionspayload: (f = msg.getGeneratecategoriesfromrestrictionspayload()) && commandpayload_pb.GenerateCategoriesFromRestrictionsPayload.toObject(includeInstance, f),
    generateschedulepayload: (f = msg.getGenerateschedulepayload()) && commandpayload_pb.GenerateSchedulePayload.toObject(includeInstance, f),
    propagatecompetitorspayload: (f = msg.getPropagatecompetitorspayload()) && commandpayload_pb.PropagateCompetitorsPayload.toObject(includeInstance, f),
    removeacademypayload: (f = msg.getRemoveacademypayload()) && commandpayload_pb.RemoveAcademyPayload.toObject(includeInstance, f),
    removecompetitorpayload: (f = msg.getRemovecompetitorpayload()) && commandpayload_pb.RemoveCompetitorPayload.toObject(includeInstance, f),
    setfightresultpayload: (f = msg.getSetfightresultpayload()) && commandpayload_pb.SetFightResultPayload.toObject(includeInstance, f),
    updateacademypayload: (f = msg.getUpdateacademypayload()) && commandpayload_pb.UpdateAcademyPayload.toObject(includeInstance, f),
    updatecompetionpropertiespayload: (f = msg.getUpdatecompetionpropertiespayload()) && commandpayload_pb.UpdateCompetionPropertiesPayload.toObject(includeInstance, f),
    updatecompetitorpayload: (f = msg.getUpdatecompetitorpayload()) && commandpayload_pb.UpdateCompetitorPayload.toObject(includeInstance, f),
    updateregistrationinfopayload: (f = msg.getUpdateregistrationinfopayload()) && commandpayload_pb.UpdateRegistrationInfoPayload.toObject(includeInstance, f),
    updatestagestatuspayload: (f = msg.getUpdatestagestatuspayload()) && commandpayload_pb.UpdateStageStatusPayload.toObject(includeInstance, f),
    bracketsgeneratedpayload: (f = msg.getBracketsgeneratedpayload()) && eventpayload_pb.BracketsGeneratedPayload.toObject(includeInstance, f),
    categoryaddedpayload: (f = msg.getCategoryaddedpayload()) && eventpayload_pb.CategoryAddedPayload.toObject(includeInstance, f),
    competitioncreatedpayload: (f = msg.getCompetitioncreatedpayload()) && eventpayload_pb.CompetitionCreatedPayload.toObject(includeInstance, f),
    competitioninfopayload: (f = msg.getCompetitioninfopayload()) && eventpayload_pb.CompetitionInfoPayload.toObject(includeInstance, f),
    competitionpropertiesupdatedpayload: (f = msg.getCompetitionpropertiesupdatedpayload()) && eventpayload_pb.CompetitionPropertiesUpdatedPayload.toObject(includeInstance, f),
    competitionstatusupdatedpayload: (f = msg.getCompetitionstatusupdatedpayload()) && eventpayload_pb.CompetitionStatusUpdatedPayload.toObject(includeInstance, f),
    competitoraddedpayload: (f = msg.getCompetitoraddedpayload()) && eventpayload_pb.CompetitorAddedPayload.toObject(includeInstance, f),
    competitorremovedpayload: (f = msg.getCompetitorremovedpayload()) && eventpayload_pb.CompetitorRemovedPayload.toObject(includeInstance, f),
    competitorspropagatedtostagepayload: (f = msg.getCompetitorspropagatedtostagepayload()) && eventpayload_pb.CompetitorsPropagatedToStagePayload.toObject(includeInstance, f),
    competitorupdatedpayload: (f = msg.getCompetitorupdatedpayload()) && eventpayload_pb.CompetitorUpdatedPayload.toObject(includeInstance, f),
    fightcompetitorsassignedpayload: (f = msg.getFightcompetitorsassignedpayload()) && eventpayload_pb.FightCompetitorsAssignedPayload.toObject(includeInstance, f),
    fighteditorchangesappliedpayload: (f = msg.getFighteditorchangesappliedpayload()) && eventpayload_pb.FightEditorChangesAppliedPayload.toObject(includeInstance, f),
    fightsaddedtostagepayload: (f = msg.getFightsaddedtostagepayload()) && eventpayload_pb.FightsAddedToStagePayload.toObject(includeInstance, f),
    fightstarttimeupdatedpayload: (f = msg.getFightstarttimeupdatedpayload()) && eventpayload_pb.FightStartTimeUpdatedPayload.toObject(includeInstance, f),
    matsupdatedpayload: (f = msg.getMatsupdatedpayload()) && eventpayload_pb.MatsUpdatedPayload.toObject(includeInstance, f),
    registrationinfoupdatedpayload: (f = msg.getRegistrationinfoupdatedpayload()) && eventpayload_pb.RegistrationInfoUpdatedPayload.toObject(includeInstance, f),
    schedulegeneratedpayload: (f = msg.getSchedulegeneratedpayload()) && eventpayload_pb.ScheduleGeneratedPayload.toObject(includeInstance, f),
    stageresultsetpayload: (f = msg.getStageresultsetpayload()) && eventpayload_pb.StageResultSetPayload.toObject(includeInstance, f),
    stagestatusupdatedpayload: (f = msg.getStagestatusupdatedpayload()) && eventpayload_pb.StageStatusUpdatedPayload.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.MessageInfo}
 */
proto.compservice.model.protobuf.MessageInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.MessageInfo;
  return proto.compservice.model.protobuf.MessageInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.MessageInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.MessageInfo}
 */
proto.compservice.model.protobuf.MessageInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCorrelationid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompetitionid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompetitorid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategoryid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMatid(value);
      break;
    case 11:
      var value = new commandpayload_pb.AddAcademyPayload;
      reader.readMessage(value,commandpayload_pb.AddAcademyPayload.deserializeBinaryFromReader);
      msg.setAddacademypayload(value);
      break;
    case 12:
      var value = new commandpayload_pb.AddCategoryPayload;
      reader.readMessage(value,commandpayload_pb.AddCategoryPayload.deserializeBinaryFromReader);
      msg.setAddcategorypayload(value);
      break;
    case 13:
      var value = new commandpayload_pb.AddCompetitorPayload;
      reader.readMessage(value,commandpayload_pb.AddCompetitorPayload.deserializeBinaryFromReader);
      msg.setAddcompetitorpayload(value);
      break;
    case 17:
      var value = new commandpayload_pb.CategoryRegistrationStatusChangePayload;
      reader.readMessage(value,commandpayload_pb.CategoryRegistrationStatusChangePayload.deserializeBinaryFromReader);
      msg.setCategoryregistrationstatuschangepayload(value);
      break;
    case 18:
      var value = new commandpayload_pb.ChangeCompetitorCategoryPayload;
      reader.readMessage(value,commandpayload_pb.ChangeCompetitorCategoryPayload.deserializeBinaryFromReader);
      msg.setChangecompetitorcategorypayload(value);
      break;
    case 19:
      var value = new commandpayload_pb.ChangeFightOrderPayload;
      reader.readMessage(value,commandpayload_pb.ChangeFightOrderPayload.deserializeBinaryFromReader);
      msg.setChangefightorderpayload(value);
      break;
    case 110:
      var value = new commandpayload_pb.CompetitorCategoryAddedPayload;
      reader.readMessage(value,commandpayload_pb.CompetitorCategoryAddedPayload.deserializeBinaryFromReader);
      msg.setCompetitorcategoryaddedpayload(value);
      break;
    case 111:
      var value = new commandpayload_pb.CreateCompetitionPayload;
      reader.readMessage(value,commandpayload_pb.CreateCompetitionPayload.deserializeBinaryFromReader);
      msg.setCreatecompetitionpayload(value);
      break;
    case 112:
      var value = new commandpayload_pb.CreateFakeCompetitorsPayload;
      reader.readMessage(value,commandpayload_pb.CreateFakeCompetitorsPayload.deserializeBinaryFromReader);
      msg.setCreatefakecompetitorspayload(value);
      break;
    case 115:
      var value = new commandpayload_pb.FightEditorApplyChangesPayload;
      reader.readMessage(value,commandpayload_pb.FightEditorApplyChangesPayload.deserializeBinaryFromReader);
      msg.setFighteditorapplychangespayload(value);
      break;
    case 116:
      var value = new commandpayload_pb.GenerateAbsoluteCategoryPayload;
      reader.readMessage(value,commandpayload_pb.GenerateAbsoluteCategoryPayload.deserializeBinaryFromReader);
      msg.setGenerateabsolutecategorypayload(value);
      break;
    case 117:
      var value = new commandpayload_pb.GenerateBracketsPayload;
      reader.readMessage(value,commandpayload_pb.GenerateBracketsPayload.deserializeBinaryFromReader);
      msg.setGeneratebracketspayload(value);
      break;
    case 118:
      var value = new commandpayload_pb.GenerateCategoriesFromRestrictionsPayload;
      reader.readMessage(value,commandpayload_pb.GenerateCategoriesFromRestrictionsPayload.deserializeBinaryFromReader);
      msg.setGeneratecategoriesfromrestrictionspayload(value);
      break;
    case 119:
      var value = new commandpayload_pb.GenerateSchedulePayload;
      reader.readMessage(value,commandpayload_pb.GenerateSchedulePayload.deserializeBinaryFromReader);
      msg.setGenerateschedulepayload(value);
      break;
    case 120:
      var value = new commandpayload_pb.PropagateCompetitorsPayload;
      reader.readMessage(value,commandpayload_pb.PropagateCompetitorsPayload.deserializeBinaryFromReader);
      msg.setPropagatecompetitorspayload(value);
      break;
    case 122:
      var value = new commandpayload_pb.RemoveAcademyPayload;
      reader.readMessage(value,commandpayload_pb.RemoveAcademyPayload.deserializeBinaryFromReader);
      msg.setRemoveacademypayload(value);
      break;
    case 123:
      var value = new commandpayload_pb.RemoveCompetitorPayload;
      reader.readMessage(value,commandpayload_pb.RemoveCompetitorPayload.deserializeBinaryFromReader);
      msg.setRemovecompetitorpayload(value);
      break;
    case 124:
      var value = new commandpayload_pb.SetFightResultPayload;
      reader.readMessage(value,commandpayload_pb.SetFightResultPayload.deserializeBinaryFromReader);
      msg.setSetfightresultpayload(value);
      break;
    case 125:
      var value = new commandpayload_pb.UpdateAcademyPayload;
      reader.readMessage(value,commandpayload_pb.UpdateAcademyPayload.deserializeBinaryFromReader);
      msg.setUpdateacademypayload(value);
      break;
    case 126:
      var value = new commandpayload_pb.UpdateCompetionPropertiesPayload;
      reader.readMessage(value,commandpayload_pb.UpdateCompetionPropertiesPayload.deserializeBinaryFromReader);
      msg.setUpdatecompetionpropertiespayload(value);
      break;
    case 127:
      var value = new commandpayload_pb.UpdateCompetitorPayload;
      reader.readMessage(value,commandpayload_pb.UpdateCompetitorPayload.deserializeBinaryFromReader);
      msg.setUpdatecompetitorpayload(value);
      break;
    case 128:
      var value = new commandpayload_pb.UpdateRegistrationInfoPayload;
      reader.readMessage(value,commandpayload_pb.UpdateRegistrationInfoPayload.deserializeBinaryFromReader);
      msg.setUpdateregistrationinfopayload(value);
      break;
    case 129:
      var value = new commandpayload_pb.UpdateStageStatusPayload;
      reader.readMessage(value,commandpayload_pb.UpdateStageStatusPayload.deserializeBinaryFromReader);
      msg.setUpdatestagestatuspayload(value);
      break;
    case 21:
      var value = new eventpayload_pb.BracketsGeneratedPayload;
      reader.readMessage(value,eventpayload_pb.BracketsGeneratedPayload.deserializeBinaryFromReader);
      msg.setBracketsgeneratedpayload(value);
      break;
    case 22:
      var value = new eventpayload_pb.CategoryAddedPayload;
      reader.readMessage(value,eventpayload_pb.CategoryAddedPayload.deserializeBinaryFromReader);
      msg.setCategoryaddedpayload(value);
      break;
    case 23:
      var value = new eventpayload_pb.CompetitionCreatedPayload;
      reader.readMessage(value,eventpayload_pb.CompetitionCreatedPayload.deserializeBinaryFromReader);
      msg.setCompetitioncreatedpayload(value);
      break;
    case 24:
      var value = new eventpayload_pb.CompetitionInfoPayload;
      reader.readMessage(value,eventpayload_pb.CompetitionInfoPayload.deserializeBinaryFromReader);
      msg.setCompetitioninfopayload(value);
      break;
    case 25:
      var value = new eventpayload_pb.CompetitionPropertiesUpdatedPayload;
      reader.readMessage(value,eventpayload_pb.CompetitionPropertiesUpdatedPayload.deserializeBinaryFromReader);
      msg.setCompetitionpropertiesupdatedpayload(value);
      break;
    case 26:
      var value = new eventpayload_pb.CompetitionStatusUpdatedPayload;
      reader.readMessage(value,eventpayload_pb.CompetitionStatusUpdatedPayload.deserializeBinaryFromReader);
      msg.setCompetitionstatusupdatedpayload(value);
      break;
    case 27:
      var value = new eventpayload_pb.CompetitorAddedPayload;
      reader.readMessage(value,eventpayload_pb.CompetitorAddedPayload.deserializeBinaryFromReader);
      msg.setCompetitoraddedpayload(value);
      break;
    case 28:
      var value = new eventpayload_pb.CompetitorRemovedPayload;
      reader.readMessage(value,eventpayload_pb.CompetitorRemovedPayload.deserializeBinaryFromReader);
      msg.setCompetitorremovedpayload(value);
      break;
    case 29:
      var value = new eventpayload_pb.CompetitorsPropagatedToStagePayload;
      reader.readMessage(value,eventpayload_pb.CompetitorsPropagatedToStagePayload.deserializeBinaryFromReader);
      msg.setCompetitorspropagatedtostagepayload(value);
      break;
    case 210:
      var value = new eventpayload_pb.CompetitorUpdatedPayload;
      reader.readMessage(value,eventpayload_pb.CompetitorUpdatedPayload.deserializeBinaryFromReader);
      msg.setCompetitorupdatedpayload(value);
      break;
    case 211:
      var value = new eventpayload_pb.FightCompetitorsAssignedPayload;
      reader.readMessage(value,eventpayload_pb.FightCompetitorsAssignedPayload.deserializeBinaryFromReader);
      msg.setFightcompetitorsassignedpayload(value);
      break;
    case 212:
      var value = new eventpayload_pb.FightEditorChangesAppliedPayload;
      reader.readMessage(value,eventpayload_pb.FightEditorChangesAppliedPayload.deserializeBinaryFromReader);
      msg.setFighteditorchangesappliedpayload(value);
      break;
    case 213:
      var value = new eventpayload_pb.FightsAddedToStagePayload;
      reader.readMessage(value,eventpayload_pb.FightsAddedToStagePayload.deserializeBinaryFromReader);
      msg.setFightsaddedtostagepayload(value);
      break;
    case 214:
      var value = new eventpayload_pb.FightStartTimeUpdatedPayload;
      reader.readMessage(value,eventpayload_pb.FightStartTimeUpdatedPayload.deserializeBinaryFromReader);
      msg.setFightstarttimeupdatedpayload(value);
      break;
    case 215:
      var value = new eventpayload_pb.MatsUpdatedPayload;
      reader.readMessage(value,eventpayload_pb.MatsUpdatedPayload.deserializeBinaryFromReader);
      msg.setMatsupdatedpayload(value);
      break;
    case 219:
      var value = new eventpayload_pb.RegistrationInfoUpdatedPayload;
      reader.readMessage(value,eventpayload_pb.RegistrationInfoUpdatedPayload.deserializeBinaryFromReader);
      msg.setRegistrationinfoupdatedpayload(value);
      break;
    case 222:
      var value = new eventpayload_pb.ScheduleGeneratedPayload;
      reader.readMessage(value,eventpayload_pb.ScheduleGeneratedPayload.deserializeBinaryFromReader);
      msg.setSchedulegeneratedpayload(value);
      break;
    case 223:
      var value = new eventpayload_pb.StageResultSetPayload;
      reader.readMessage(value,eventpayload_pb.StageResultSetPayload.deserializeBinaryFromReader);
      msg.setStageresultsetpayload(value);
      break;
    case 224:
      var value = new eventpayload_pb.StageStatusUpdatedPayload;
      reader.readMessage(value,eventpayload_pb.StageStatusUpdatedPayload.deserializeBinaryFromReader);
      msg.setStagestatusupdatedpayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.MessageInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.MessageInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.MessageInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getAddacademypayload();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      commandpayload_pb.AddAcademyPayload.serializeBinaryToWriter
    );
  }
  f = message.getAddcategorypayload();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      commandpayload_pb.AddCategoryPayload.serializeBinaryToWriter
    );
  }
  f = message.getAddcompetitorpayload();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      commandpayload_pb.AddCompetitorPayload.serializeBinaryToWriter
    );
  }
  f = message.getCategoryregistrationstatuschangepayload();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      commandpayload_pb.CategoryRegistrationStatusChangePayload.serializeBinaryToWriter
    );
  }
  f = message.getChangecompetitorcategorypayload();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      commandpayload_pb.ChangeCompetitorCategoryPayload.serializeBinaryToWriter
    );
  }
  f = message.getChangefightorderpayload();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      commandpayload_pb.ChangeFightOrderPayload.serializeBinaryToWriter
    );
  }
  f = message.getCompetitorcategoryaddedpayload();
  if (f != null) {
    writer.writeMessage(
      110,
      f,
      commandpayload_pb.CompetitorCategoryAddedPayload.serializeBinaryToWriter
    );
  }
  f = message.getCreatecompetitionpayload();
  if (f != null) {
    writer.writeMessage(
      111,
      f,
      commandpayload_pb.CreateCompetitionPayload.serializeBinaryToWriter
    );
  }
  f = message.getCreatefakecompetitorspayload();
  if (f != null) {
    writer.writeMessage(
      112,
      f,
      commandpayload_pb.CreateFakeCompetitorsPayload.serializeBinaryToWriter
    );
  }
  f = message.getFighteditorapplychangespayload();
  if (f != null) {
    writer.writeMessage(
      115,
      f,
      commandpayload_pb.FightEditorApplyChangesPayload.serializeBinaryToWriter
    );
  }
  f = message.getGenerateabsolutecategorypayload();
  if (f != null) {
    writer.writeMessage(
      116,
      f,
      commandpayload_pb.GenerateAbsoluteCategoryPayload.serializeBinaryToWriter
    );
  }
  f = message.getGeneratebracketspayload();
  if (f != null) {
    writer.writeMessage(
      117,
      f,
      commandpayload_pb.GenerateBracketsPayload.serializeBinaryToWriter
    );
  }
  f = message.getGeneratecategoriesfromrestrictionspayload();
  if (f != null) {
    writer.writeMessage(
      118,
      f,
      commandpayload_pb.GenerateCategoriesFromRestrictionsPayload.serializeBinaryToWriter
    );
  }
  f = message.getGenerateschedulepayload();
  if (f != null) {
    writer.writeMessage(
      119,
      f,
      commandpayload_pb.GenerateSchedulePayload.serializeBinaryToWriter
    );
  }
  f = message.getPropagatecompetitorspayload();
  if (f != null) {
    writer.writeMessage(
      120,
      f,
      commandpayload_pb.PropagateCompetitorsPayload.serializeBinaryToWriter
    );
  }
  f = message.getRemoveacademypayload();
  if (f != null) {
    writer.writeMessage(
      122,
      f,
      commandpayload_pb.RemoveAcademyPayload.serializeBinaryToWriter
    );
  }
  f = message.getRemovecompetitorpayload();
  if (f != null) {
    writer.writeMessage(
      123,
      f,
      commandpayload_pb.RemoveCompetitorPayload.serializeBinaryToWriter
    );
  }
  f = message.getSetfightresultpayload();
  if (f != null) {
    writer.writeMessage(
      124,
      f,
      commandpayload_pb.SetFightResultPayload.serializeBinaryToWriter
    );
  }
  f = message.getUpdateacademypayload();
  if (f != null) {
    writer.writeMessage(
      125,
      f,
      commandpayload_pb.UpdateAcademyPayload.serializeBinaryToWriter
    );
  }
  f = message.getUpdatecompetionpropertiespayload();
  if (f != null) {
    writer.writeMessage(
      126,
      f,
      commandpayload_pb.UpdateCompetionPropertiesPayload.serializeBinaryToWriter
    );
  }
  f = message.getUpdatecompetitorpayload();
  if (f != null) {
    writer.writeMessage(
      127,
      f,
      commandpayload_pb.UpdateCompetitorPayload.serializeBinaryToWriter
    );
  }
  f = message.getUpdateregistrationinfopayload();
  if (f != null) {
    writer.writeMessage(
      128,
      f,
      commandpayload_pb.UpdateRegistrationInfoPayload.serializeBinaryToWriter
    );
  }
  f = message.getUpdatestagestatuspayload();
  if (f != null) {
    writer.writeMessage(
      129,
      f,
      commandpayload_pb.UpdateStageStatusPayload.serializeBinaryToWriter
    );
  }
  f = message.getBracketsgeneratedpayload();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      eventpayload_pb.BracketsGeneratedPayload.serializeBinaryToWriter
    );
  }
  f = message.getCategoryaddedpayload();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      eventpayload_pb.CategoryAddedPayload.serializeBinaryToWriter
    );
  }
  f = message.getCompetitioncreatedpayload();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      eventpayload_pb.CompetitionCreatedPayload.serializeBinaryToWriter
    );
  }
  f = message.getCompetitioninfopayload();
  if (f != null) {
    writer.writeMessage(
      24,
      f,
      eventpayload_pb.CompetitionInfoPayload.serializeBinaryToWriter
    );
  }
  f = message.getCompetitionpropertiesupdatedpayload();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      eventpayload_pb.CompetitionPropertiesUpdatedPayload.serializeBinaryToWriter
    );
  }
  f = message.getCompetitionstatusupdatedpayload();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      eventpayload_pb.CompetitionStatusUpdatedPayload.serializeBinaryToWriter
    );
  }
  f = message.getCompetitoraddedpayload();
  if (f != null) {
    writer.writeMessage(
      27,
      f,
      eventpayload_pb.CompetitorAddedPayload.serializeBinaryToWriter
    );
  }
  f = message.getCompetitorremovedpayload();
  if (f != null) {
    writer.writeMessage(
      28,
      f,
      eventpayload_pb.CompetitorRemovedPayload.serializeBinaryToWriter
    );
  }
  f = message.getCompetitorspropagatedtostagepayload();
  if (f != null) {
    writer.writeMessage(
      29,
      f,
      eventpayload_pb.CompetitorsPropagatedToStagePayload.serializeBinaryToWriter
    );
  }
  f = message.getCompetitorupdatedpayload();
  if (f != null) {
    writer.writeMessage(
      210,
      f,
      eventpayload_pb.CompetitorUpdatedPayload.serializeBinaryToWriter
    );
  }
  f = message.getFightcompetitorsassignedpayload();
  if (f != null) {
    writer.writeMessage(
      211,
      f,
      eventpayload_pb.FightCompetitorsAssignedPayload.serializeBinaryToWriter
    );
  }
  f = message.getFighteditorchangesappliedpayload();
  if (f != null) {
    writer.writeMessage(
      212,
      f,
      eventpayload_pb.FightEditorChangesAppliedPayload.serializeBinaryToWriter
    );
  }
  f = message.getFightsaddedtostagepayload();
  if (f != null) {
    writer.writeMessage(
      213,
      f,
      eventpayload_pb.FightsAddedToStagePayload.serializeBinaryToWriter
    );
  }
  f = message.getFightstarttimeupdatedpayload();
  if (f != null) {
    writer.writeMessage(
      214,
      f,
      eventpayload_pb.FightStartTimeUpdatedPayload.serializeBinaryToWriter
    );
  }
  f = message.getMatsupdatedpayload();
  if (f != null) {
    writer.writeMessage(
      215,
      f,
      eventpayload_pb.MatsUpdatedPayload.serializeBinaryToWriter
    );
  }
  f = message.getRegistrationinfoupdatedpayload();
  if (f != null) {
    writer.writeMessage(
      219,
      f,
      eventpayload_pb.RegistrationInfoUpdatedPayload.serializeBinaryToWriter
    );
  }
  f = message.getSchedulegeneratedpayload();
  if (f != null) {
    writer.writeMessage(
      222,
      f,
      eventpayload_pb.ScheduleGeneratedPayload.serializeBinaryToWriter
    );
  }
  f = message.getStageresultsetpayload();
  if (f != null) {
    writer.writeMessage(
      223,
      f,
      eventpayload_pb.StageResultSetPayload.serializeBinaryToWriter
    );
  }
  f = message.getStagestatusupdatedpayload();
  if (f != null) {
    writer.writeMessage(
      224,
      f,
      eventpayload_pb.StageStatusUpdatedPayload.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.setId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string correlationId = 2;
 * @return {string}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCorrelationid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.setCorrelationid = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCorrelationid = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCorrelationid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string competitionId = 3;
 * @return {string}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitionid = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitionid = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitionid = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string competitorId = 4;
 * @return {string}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitorid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitorid = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitorid = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitorid = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string categoryId = 5;
 * @return {string}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCategoryid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.setCategoryid = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCategoryid = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCategoryid = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string matId = 6;
 * @return {string}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getMatid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.setMatid = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearMatid = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasMatid = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional AddAcademyPayload addAcademyPayload = 11;
 * @return {?proto.compservice.model.protobuf.AddAcademyPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getAddacademypayload = function() {
  return /** @type{?proto.compservice.model.protobuf.AddAcademyPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.AddAcademyPayload, 11));
};


/**
 * @param {?proto.compservice.model.protobuf.AddAcademyPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setAddacademypayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearAddacademypayload = function() {
  return this.setAddacademypayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasAddacademypayload = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional AddCategoryPayload addCategoryPayload = 12;
 * @return {?proto.compservice.model.protobuf.AddCategoryPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getAddcategorypayload = function() {
  return /** @type{?proto.compservice.model.protobuf.AddCategoryPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.AddCategoryPayload, 12));
};


/**
 * @param {?proto.compservice.model.protobuf.AddCategoryPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setAddcategorypayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearAddcategorypayload = function() {
  return this.setAddcategorypayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasAddcategorypayload = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional AddCompetitorPayload addCompetitorPayload = 13;
 * @return {?proto.compservice.model.protobuf.AddCompetitorPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getAddcompetitorpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.AddCompetitorPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.AddCompetitorPayload, 13));
};


/**
 * @param {?proto.compservice.model.protobuf.AddCompetitorPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setAddcompetitorpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 13, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearAddcompetitorpayload = function() {
  return this.setAddcompetitorpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasAddcompetitorpayload = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional CategoryRegistrationStatusChangePayload categoryRegistrationStatusChangePayload = 17;
 * @return {?proto.compservice.model.protobuf.CategoryRegistrationStatusChangePayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCategoryregistrationstatuschangepayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CategoryRegistrationStatusChangePayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.CategoryRegistrationStatusChangePayload, 17));
};


/**
 * @param {?proto.compservice.model.protobuf.CategoryRegistrationStatusChangePayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCategoryregistrationstatuschangepayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 17, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCategoryregistrationstatuschangepayload = function() {
  return this.setCategoryregistrationstatuschangepayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCategoryregistrationstatuschangepayload = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional ChangeCompetitorCategoryPayload changeCompetitorCategoryPayload = 18;
 * @return {?proto.compservice.model.protobuf.ChangeCompetitorCategoryPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getChangecompetitorcategorypayload = function() {
  return /** @type{?proto.compservice.model.protobuf.ChangeCompetitorCategoryPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.ChangeCompetitorCategoryPayload, 18));
};


/**
 * @param {?proto.compservice.model.protobuf.ChangeCompetitorCategoryPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setChangecompetitorcategorypayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 18, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearChangecompetitorcategorypayload = function() {
  return this.setChangecompetitorcategorypayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasChangecompetitorcategorypayload = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional ChangeFightOrderPayload changeFightOrderPayload = 19;
 * @return {?proto.compservice.model.protobuf.ChangeFightOrderPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getChangefightorderpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.ChangeFightOrderPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.ChangeFightOrderPayload, 19));
};


/**
 * @param {?proto.compservice.model.protobuf.ChangeFightOrderPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setChangefightorderpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 19, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearChangefightorderpayload = function() {
  return this.setChangefightorderpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasChangefightorderpayload = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional CompetitorCategoryAddedPayload competitorCategoryAddedPayload = 110;
 * @return {?proto.compservice.model.protobuf.CompetitorCategoryAddedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitorcategoryaddedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CompetitorCategoryAddedPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.CompetitorCategoryAddedPayload, 110));
};


/**
 * @param {?proto.compservice.model.protobuf.CompetitorCategoryAddedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitorcategoryaddedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 110, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitorcategoryaddedpayload = function() {
  return this.setCompetitorcategoryaddedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitorcategoryaddedpayload = function() {
  return jspb.Message.getField(this, 110) != null;
};


/**
 * optional CreateCompetitionPayload createCompetitionPayload = 111;
 * @return {?proto.compservice.model.protobuf.CreateCompetitionPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCreatecompetitionpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CreateCompetitionPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.CreateCompetitionPayload, 111));
};


/**
 * @param {?proto.compservice.model.protobuf.CreateCompetitionPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCreatecompetitionpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 111, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCreatecompetitionpayload = function() {
  return this.setCreatecompetitionpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCreatecompetitionpayload = function() {
  return jspb.Message.getField(this, 111) != null;
};


/**
 * optional CreateFakeCompetitorsPayload createFakeCompetitorsPayload = 112;
 * @return {?proto.compservice.model.protobuf.CreateFakeCompetitorsPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCreatefakecompetitorspayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CreateFakeCompetitorsPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.CreateFakeCompetitorsPayload, 112));
};


/**
 * @param {?proto.compservice.model.protobuf.CreateFakeCompetitorsPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCreatefakecompetitorspayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 112, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCreatefakecompetitorspayload = function() {
  return this.setCreatefakecompetitorspayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCreatefakecompetitorspayload = function() {
  return jspb.Message.getField(this, 112) != null;
};


/**
 * optional FightEditorApplyChangesPayload fightEditorApplyChangesPayload = 115;
 * @return {?proto.compservice.model.protobuf.FightEditorApplyChangesPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getFighteditorapplychangespayload = function() {
  return /** @type{?proto.compservice.model.protobuf.FightEditorApplyChangesPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.FightEditorApplyChangesPayload, 115));
};


/**
 * @param {?proto.compservice.model.protobuf.FightEditorApplyChangesPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setFighteditorapplychangespayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 115, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearFighteditorapplychangespayload = function() {
  return this.setFighteditorapplychangespayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasFighteditorapplychangespayload = function() {
  return jspb.Message.getField(this, 115) != null;
};


/**
 * optional GenerateAbsoluteCategoryPayload generateAbsoluteCategoryPayload = 116;
 * @return {?proto.compservice.model.protobuf.GenerateAbsoluteCategoryPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getGenerateabsolutecategorypayload = function() {
  return /** @type{?proto.compservice.model.protobuf.GenerateAbsoluteCategoryPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.GenerateAbsoluteCategoryPayload, 116));
};


/**
 * @param {?proto.compservice.model.protobuf.GenerateAbsoluteCategoryPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setGenerateabsolutecategorypayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 116, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearGenerateabsolutecategorypayload = function() {
  return this.setGenerateabsolutecategorypayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasGenerateabsolutecategorypayload = function() {
  return jspb.Message.getField(this, 116) != null;
};


/**
 * optional GenerateBracketsPayload generateBracketsPayload = 117;
 * @return {?proto.compservice.model.protobuf.GenerateBracketsPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getGeneratebracketspayload = function() {
  return /** @type{?proto.compservice.model.protobuf.GenerateBracketsPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.GenerateBracketsPayload, 117));
};


/**
 * @param {?proto.compservice.model.protobuf.GenerateBracketsPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setGeneratebracketspayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 117, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearGeneratebracketspayload = function() {
  return this.setGeneratebracketspayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasGeneratebracketspayload = function() {
  return jspb.Message.getField(this, 117) != null;
};


/**
 * optional GenerateCategoriesFromRestrictionsPayload generateCategoriesFromRestrictionsPayload = 118;
 * @return {?proto.compservice.model.protobuf.GenerateCategoriesFromRestrictionsPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getGeneratecategoriesfromrestrictionspayload = function() {
  return /** @type{?proto.compservice.model.protobuf.GenerateCategoriesFromRestrictionsPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.GenerateCategoriesFromRestrictionsPayload, 118));
};


/**
 * @param {?proto.compservice.model.protobuf.GenerateCategoriesFromRestrictionsPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setGeneratecategoriesfromrestrictionspayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 118, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearGeneratecategoriesfromrestrictionspayload = function() {
  return this.setGeneratecategoriesfromrestrictionspayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasGeneratecategoriesfromrestrictionspayload = function() {
  return jspb.Message.getField(this, 118) != null;
};


/**
 * optional GenerateSchedulePayload generateSchedulePayload = 119;
 * @return {?proto.compservice.model.protobuf.GenerateSchedulePayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getGenerateschedulepayload = function() {
  return /** @type{?proto.compservice.model.protobuf.GenerateSchedulePayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.GenerateSchedulePayload, 119));
};


/**
 * @param {?proto.compservice.model.protobuf.GenerateSchedulePayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setGenerateschedulepayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 119, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearGenerateschedulepayload = function() {
  return this.setGenerateschedulepayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasGenerateschedulepayload = function() {
  return jspb.Message.getField(this, 119) != null;
};


/**
 * optional PropagateCompetitorsPayload propagateCompetitorsPayload = 120;
 * @return {?proto.compservice.model.protobuf.PropagateCompetitorsPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getPropagatecompetitorspayload = function() {
  return /** @type{?proto.compservice.model.protobuf.PropagateCompetitorsPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.PropagateCompetitorsPayload, 120));
};


/**
 * @param {?proto.compservice.model.protobuf.PropagateCompetitorsPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setPropagatecompetitorspayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 120, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearPropagatecompetitorspayload = function() {
  return this.setPropagatecompetitorspayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasPropagatecompetitorspayload = function() {
  return jspb.Message.getField(this, 120) != null;
};


/**
 * optional RemoveAcademyPayload removeAcademyPayload = 122;
 * @return {?proto.compservice.model.protobuf.RemoveAcademyPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getRemoveacademypayload = function() {
  return /** @type{?proto.compservice.model.protobuf.RemoveAcademyPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.RemoveAcademyPayload, 122));
};


/**
 * @param {?proto.compservice.model.protobuf.RemoveAcademyPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setRemoveacademypayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 122, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearRemoveacademypayload = function() {
  return this.setRemoveacademypayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasRemoveacademypayload = function() {
  return jspb.Message.getField(this, 122) != null;
};


/**
 * optional RemoveCompetitorPayload removeCompetitorPayload = 123;
 * @return {?proto.compservice.model.protobuf.RemoveCompetitorPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getRemovecompetitorpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.RemoveCompetitorPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.RemoveCompetitorPayload, 123));
};


/**
 * @param {?proto.compservice.model.protobuf.RemoveCompetitorPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setRemovecompetitorpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 123, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearRemovecompetitorpayload = function() {
  return this.setRemovecompetitorpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasRemovecompetitorpayload = function() {
  return jspb.Message.getField(this, 123) != null;
};


/**
 * optional SetFightResultPayload setFightResultPayload = 124;
 * @return {?proto.compservice.model.protobuf.SetFightResultPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getSetfightresultpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.SetFightResultPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.SetFightResultPayload, 124));
};


/**
 * @param {?proto.compservice.model.protobuf.SetFightResultPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setSetfightresultpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 124, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearSetfightresultpayload = function() {
  return this.setSetfightresultpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasSetfightresultpayload = function() {
  return jspb.Message.getField(this, 124) != null;
};


/**
 * optional UpdateAcademyPayload updateAcademyPayload = 125;
 * @return {?proto.compservice.model.protobuf.UpdateAcademyPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getUpdateacademypayload = function() {
  return /** @type{?proto.compservice.model.protobuf.UpdateAcademyPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.UpdateAcademyPayload, 125));
};


/**
 * @param {?proto.compservice.model.protobuf.UpdateAcademyPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setUpdateacademypayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 125, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearUpdateacademypayload = function() {
  return this.setUpdateacademypayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasUpdateacademypayload = function() {
  return jspb.Message.getField(this, 125) != null;
};


/**
 * optional UpdateCompetionPropertiesPayload updateCompetionPropertiesPayload = 126;
 * @return {?proto.compservice.model.protobuf.UpdateCompetionPropertiesPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getUpdatecompetionpropertiespayload = function() {
  return /** @type{?proto.compservice.model.protobuf.UpdateCompetionPropertiesPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.UpdateCompetionPropertiesPayload, 126));
};


/**
 * @param {?proto.compservice.model.protobuf.UpdateCompetionPropertiesPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setUpdatecompetionpropertiespayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 126, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearUpdatecompetionpropertiespayload = function() {
  return this.setUpdatecompetionpropertiespayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasUpdatecompetionpropertiespayload = function() {
  return jspb.Message.getField(this, 126) != null;
};


/**
 * optional UpdateCompetitorPayload updateCompetitorPayload = 127;
 * @return {?proto.compservice.model.protobuf.UpdateCompetitorPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getUpdatecompetitorpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.UpdateCompetitorPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.UpdateCompetitorPayload, 127));
};


/**
 * @param {?proto.compservice.model.protobuf.UpdateCompetitorPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setUpdatecompetitorpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 127, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearUpdatecompetitorpayload = function() {
  return this.setUpdatecompetitorpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasUpdatecompetitorpayload = function() {
  return jspb.Message.getField(this, 127) != null;
};


/**
 * optional UpdateRegistrationInfoPayload updateRegistrationInfoPayload = 128;
 * @return {?proto.compservice.model.protobuf.UpdateRegistrationInfoPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getUpdateregistrationinfopayload = function() {
  return /** @type{?proto.compservice.model.protobuf.UpdateRegistrationInfoPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.UpdateRegistrationInfoPayload, 128));
};


/**
 * @param {?proto.compservice.model.protobuf.UpdateRegistrationInfoPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setUpdateregistrationinfopayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 128, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearUpdateregistrationinfopayload = function() {
  return this.setUpdateregistrationinfopayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasUpdateregistrationinfopayload = function() {
  return jspb.Message.getField(this, 128) != null;
};


/**
 * optional UpdateStageStatusPayload updateStageStatusPayload = 129;
 * @return {?proto.compservice.model.protobuf.UpdateStageStatusPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getUpdatestagestatuspayload = function() {
  return /** @type{?proto.compservice.model.protobuf.UpdateStageStatusPayload} */ (
    jspb.Message.getWrapperField(this, commandpayload_pb.UpdateStageStatusPayload, 129));
};


/**
 * @param {?proto.compservice.model.protobuf.UpdateStageStatusPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setUpdatestagestatuspayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 129, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearUpdatestagestatuspayload = function() {
  return this.setUpdatestagestatuspayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasUpdatestagestatuspayload = function() {
  return jspb.Message.getField(this, 129) != null;
};


/**
 * optional BracketsGeneratedPayload bracketsGeneratedPayload = 21;
 * @return {?proto.compservice.model.protobuf.BracketsGeneratedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getBracketsgeneratedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.BracketsGeneratedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.BracketsGeneratedPayload, 21));
};


/**
 * @param {?proto.compservice.model.protobuf.BracketsGeneratedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setBracketsgeneratedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 21, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearBracketsgeneratedpayload = function() {
  return this.setBracketsgeneratedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasBracketsgeneratedpayload = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional CategoryAddedPayload categoryAddedPayload = 22;
 * @return {?proto.compservice.model.protobuf.CategoryAddedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCategoryaddedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CategoryAddedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.CategoryAddedPayload, 22));
};


/**
 * @param {?proto.compservice.model.protobuf.CategoryAddedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCategoryaddedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 22, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCategoryaddedpayload = function() {
  return this.setCategoryaddedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCategoryaddedpayload = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional CompetitionCreatedPayload competitionCreatedPayload = 23;
 * @return {?proto.compservice.model.protobuf.CompetitionCreatedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitioncreatedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CompetitionCreatedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.CompetitionCreatedPayload, 23));
};


/**
 * @param {?proto.compservice.model.protobuf.CompetitionCreatedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitioncreatedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 23, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitioncreatedpayload = function() {
  return this.setCompetitioncreatedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitioncreatedpayload = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional CompetitionInfoPayload competitionInfoPayload = 24;
 * @return {?proto.compservice.model.protobuf.CompetitionInfoPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitioninfopayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CompetitionInfoPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.CompetitionInfoPayload, 24));
};


/**
 * @param {?proto.compservice.model.protobuf.CompetitionInfoPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitioninfopayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 24, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitioninfopayload = function() {
  return this.setCompetitioninfopayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitioninfopayload = function() {
  return jspb.Message.getField(this, 24) != null;
};


/**
 * optional CompetitionPropertiesUpdatedPayload competitionPropertiesUpdatedPayload = 25;
 * @return {?proto.compservice.model.protobuf.CompetitionPropertiesUpdatedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitionpropertiesupdatedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CompetitionPropertiesUpdatedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.CompetitionPropertiesUpdatedPayload, 25));
};


/**
 * @param {?proto.compservice.model.protobuf.CompetitionPropertiesUpdatedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitionpropertiesupdatedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 25, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitionpropertiesupdatedpayload = function() {
  return this.setCompetitionpropertiesupdatedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitionpropertiesupdatedpayload = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional CompetitionStatusUpdatedPayload competitionStatusUpdatedPayload = 26;
 * @return {?proto.compservice.model.protobuf.CompetitionStatusUpdatedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitionstatusupdatedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CompetitionStatusUpdatedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.CompetitionStatusUpdatedPayload, 26));
};


/**
 * @param {?proto.compservice.model.protobuf.CompetitionStatusUpdatedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitionstatusupdatedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 26, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitionstatusupdatedpayload = function() {
  return this.setCompetitionstatusupdatedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitionstatusupdatedpayload = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional CompetitorAddedPayload competitorAddedPayload = 27;
 * @return {?proto.compservice.model.protobuf.CompetitorAddedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitoraddedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CompetitorAddedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.CompetitorAddedPayload, 27));
};


/**
 * @param {?proto.compservice.model.protobuf.CompetitorAddedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitoraddedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 27, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitoraddedpayload = function() {
  return this.setCompetitoraddedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitoraddedpayload = function() {
  return jspb.Message.getField(this, 27) != null;
};


/**
 * optional CompetitorRemovedPayload competitorRemovedPayload = 28;
 * @return {?proto.compservice.model.protobuf.CompetitorRemovedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitorremovedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CompetitorRemovedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.CompetitorRemovedPayload, 28));
};


/**
 * @param {?proto.compservice.model.protobuf.CompetitorRemovedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitorremovedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 28, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitorremovedpayload = function() {
  return this.setCompetitorremovedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitorremovedpayload = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional CompetitorsPropagatedToStagePayload competitorsPropagatedToStagePayload = 29;
 * @return {?proto.compservice.model.protobuf.CompetitorsPropagatedToStagePayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitorspropagatedtostagepayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CompetitorsPropagatedToStagePayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.CompetitorsPropagatedToStagePayload, 29));
};


/**
 * @param {?proto.compservice.model.protobuf.CompetitorsPropagatedToStagePayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitorspropagatedtostagepayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 29, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitorspropagatedtostagepayload = function() {
  return this.setCompetitorspropagatedtostagepayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitorspropagatedtostagepayload = function() {
  return jspb.Message.getField(this, 29) != null;
};


/**
 * optional CompetitorUpdatedPayload competitorUpdatedPayload = 210;
 * @return {?proto.compservice.model.protobuf.CompetitorUpdatedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getCompetitorupdatedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.CompetitorUpdatedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.CompetitorUpdatedPayload, 210));
};


/**
 * @param {?proto.compservice.model.protobuf.CompetitorUpdatedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setCompetitorupdatedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 210, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearCompetitorupdatedpayload = function() {
  return this.setCompetitorupdatedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasCompetitorupdatedpayload = function() {
  return jspb.Message.getField(this, 210) != null;
};


/**
 * optional FightCompetitorsAssignedPayload fightCompetitorsAssignedPayload = 211;
 * @return {?proto.compservice.model.protobuf.FightCompetitorsAssignedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getFightcompetitorsassignedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.FightCompetitorsAssignedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.FightCompetitorsAssignedPayload, 211));
};


/**
 * @param {?proto.compservice.model.protobuf.FightCompetitorsAssignedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setFightcompetitorsassignedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 211, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearFightcompetitorsassignedpayload = function() {
  return this.setFightcompetitorsassignedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasFightcompetitorsassignedpayload = function() {
  return jspb.Message.getField(this, 211) != null;
};


/**
 * optional FightEditorChangesAppliedPayload fightEditorChangesAppliedPayload = 212;
 * @return {?proto.compservice.model.protobuf.FightEditorChangesAppliedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getFighteditorchangesappliedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.FightEditorChangesAppliedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.FightEditorChangesAppliedPayload, 212));
};


/**
 * @param {?proto.compservice.model.protobuf.FightEditorChangesAppliedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setFighteditorchangesappliedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 212, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearFighteditorchangesappliedpayload = function() {
  return this.setFighteditorchangesappliedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasFighteditorchangesappliedpayload = function() {
  return jspb.Message.getField(this, 212) != null;
};


/**
 * optional FightsAddedToStagePayload fightsAddedToStagePayload = 213;
 * @return {?proto.compservice.model.protobuf.FightsAddedToStagePayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getFightsaddedtostagepayload = function() {
  return /** @type{?proto.compservice.model.protobuf.FightsAddedToStagePayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.FightsAddedToStagePayload, 213));
};


/**
 * @param {?proto.compservice.model.protobuf.FightsAddedToStagePayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setFightsaddedtostagepayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 213, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearFightsaddedtostagepayload = function() {
  return this.setFightsaddedtostagepayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasFightsaddedtostagepayload = function() {
  return jspb.Message.getField(this, 213) != null;
};


/**
 * optional FightStartTimeUpdatedPayload fightStartTimeUpdatedPayload = 214;
 * @return {?proto.compservice.model.protobuf.FightStartTimeUpdatedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getFightstarttimeupdatedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.FightStartTimeUpdatedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.FightStartTimeUpdatedPayload, 214));
};


/**
 * @param {?proto.compservice.model.protobuf.FightStartTimeUpdatedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setFightstarttimeupdatedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 214, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearFightstarttimeupdatedpayload = function() {
  return this.setFightstarttimeupdatedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasFightstarttimeupdatedpayload = function() {
  return jspb.Message.getField(this, 214) != null;
};


/**
 * optional MatsUpdatedPayload matsUpdatedPayload = 215;
 * @return {?proto.compservice.model.protobuf.MatsUpdatedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getMatsupdatedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.MatsUpdatedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.MatsUpdatedPayload, 215));
};


/**
 * @param {?proto.compservice.model.protobuf.MatsUpdatedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setMatsupdatedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 215, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearMatsupdatedpayload = function() {
  return this.setMatsupdatedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasMatsupdatedpayload = function() {
  return jspb.Message.getField(this, 215) != null;
};


/**
 * optional RegistrationInfoUpdatedPayload registrationInfoUpdatedPayload = 219;
 * @return {?proto.compservice.model.protobuf.RegistrationInfoUpdatedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getRegistrationinfoupdatedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.RegistrationInfoUpdatedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.RegistrationInfoUpdatedPayload, 219));
};


/**
 * @param {?proto.compservice.model.protobuf.RegistrationInfoUpdatedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setRegistrationinfoupdatedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 219, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearRegistrationinfoupdatedpayload = function() {
  return this.setRegistrationinfoupdatedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasRegistrationinfoupdatedpayload = function() {
  return jspb.Message.getField(this, 219) != null;
};


/**
 * optional ScheduleGeneratedPayload scheduleGeneratedPayload = 222;
 * @return {?proto.compservice.model.protobuf.ScheduleGeneratedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getSchedulegeneratedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.ScheduleGeneratedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.ScheduleGeneratedPayload, 222));
};


/**
 * @param {?proto.compservice.model.protobuf.ScheduleGeneratedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setSchedulegeneratedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 222, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearSchedulegeneratedpayload = function() {
  return this.setSchedulegeneratedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasSchedulegeneratedpayload = function() {
  return jspb.Message.getField(this, 222) != null;
};


/**
 * optional StageResultSetPayload stageResultSetPayload = 223;
 * @return {?proto.compservice.model.protobuf.StageResultSetPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getStageresultsetpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.StageResultSetPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.StageResultSetPayload, 223));
};


/**
 * @param {?proto.compservice.model.protobuf.StageResultSetPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setStageresultsetpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 223, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearStageresultsetpayload = function() {
  return this.setStageresultsetpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasStageresultsetpayload = function() {
  return jspb.Message.getField(this, 223) != null;
};


/**
 * optional StageStatusUpdatedPayload stageStatusUpdatedPayload = 224;
 * @return {?proto.compservice.model.protobuf.StageStatusUpdatedPayload}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.getStagestatusupdatedpayload = function() {
  return /** @type{?proto.compservice.model.protobuf.StageStatusUpdatedPayload} */ (
    jspb.Message.getWrapperField(this, eventpayload_pb.StageStatusUpdatedPayload, 224));
};


/**
 * @param {?proto.compservice.model.protobuf.StageStatusUpdatedPayload|undefined} value
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
*/
proto.compservice.model.protobuf.MessageInfo.prototype.setStagestatusupdatedpayload = function(value) {
  return jspb.Message.setOneofWrapperField(this, 224, proto.compservice.model.protobuf.MessageInfo.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.MessageInfo} returns this
 */
proto.compservice.model.protobuf.MessageInfo.prototype.clearStagestatusupdatedpayload = function() {
  return this.setStagestatusupdatedpayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.MessageInfo.prototype.hasStagestatusupdatedpayload = function() {
  return jspb.Message.getField(this, 224) != null;
};


goog.object.extend(exports, proto.compservice.model.protobuf);
