// source: command.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.compservice.model.protobuf.Command', null, global);
goog.exportSymbol('proto.compservice.model.protobuf.CommandType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.compservice.model.protobuf.Command = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.compservice.model.protobuf.Command, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.compservice.model.protobuf.Command.displayName = 'proto.compservice.model.protobuf.Command';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.compservice.model.protobuf.Command.prototype.toObject = function(opt_includeInstance) {
  return proto.compservice.model.protobuf.Command.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.compservice.model.protobuf.Command} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.Command.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 4, 0),
    messageinfo: (f = msg.getMessageinfo()) && common_pb.MessageInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.compservice.model.protobuf.Command}
 */
proto.compservice.model.protobuf.Command.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.compservice.model.protobuf.Command;
  return proto.compservice.model.protobuf.Command.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.compservice.model.protobuf.Command} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.compservice.model.protobuf.Command}
 */
proto.compservice.model.protobuf.Command.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 4:
      var value = /** @type {!proto.compservice.model.protobuf.CommandType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = new common_pb.MessageInfo;
      reader.readMessage(value,common_pb.MessageInfo.deserializeBinaryFromReader);
      msg.setMessageinfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.compservice.model.protobuf.Command.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.compservice.model.protobuf.Command.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.compservice.model.protobuf.Command} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.compservice.model.protobuf.Command.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getMessageinfo();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      common_pb.MessageInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional CommandType type = 4;
 * @return {!proto.compservice.model.protobuf.CommandType}
 */
proto.compservice.model.protobuf.Command.prototype.getType = function() {
  return /** @type {!proto.compservice.model.protobuf.CommandType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.compservice.model.protobuf.CommandType} value
 * @return {!proto.compservice.model.protobuf.Command} returns this
 */
proto.compservice.model.protobuf.Command.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional MessageInfo messageInfo = 5;
 * @return {?proto.compservice.model.protobuf.MessageInfo}
 */
proto.compservice.model.protobuf.Command.prototype.getMessageinfo = function() {
  return /** @type{?proto.compservice.model.protobuf.MessageInfo} */ (
    jspb.Message.getWrapperField(this, common_pb.MessageInfo, 5));
};


/**
 * @param {?proto.compservice.model.protobuf.MessageInfo|undefined} value
 * @return {!proto.compservice.model.protobuf.Command} returns this
*/
proto.compservice.model.protobuf.Command.prototype.setMessageinfo = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.compservice.model.protobuf.Command} returns this
 */
proto.compservice.model.protobuf.Command.prototype.clearMessageinfo = function() {
  return this.setMessageinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.compservice.model.protobuf.Command.prototype.hasMessageinfo = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.compservice.model.protobuf.CommandType = {
  COMMAND_TYPE_UNKNOWN: 0,
  ADD_ACADEMY_COMMAND: 1,
  ADD_CATEGORY_COMMAND: 2,
  ADD_COMPETITOR_COMMAND: 3,
  CHANGE_CATEGORY_REGISTRATION_STATUS_COMMAND: 8,
  CHANGE_COMPETITOR_CATEGORY_COMMAND: 9,
  CREATE_COMPETITION_COMMAND: 10,
  CREATE_FAKE_COMPETITORS_COMMAND: 11,
  DASHBOARD_FIGHT_ORDER_CHANGE_COMMAND: 12,
  DASHBOARD_SET_FIGHT_RESULT_COMMAND: 13,
  DELETE_CATEGORY_COMMAND: 14,
  DELETE_COMPETITION_COMMAND: 15,
  DROP_ALL_BRACKETS_COMMAND: 18,
  DROP_CATEGORY_BRACKETS_COMMAND: 19,
  DROP_SCHEDULE_COMMAND: 20,
  FIGHTS_EDITOR_APPLY_CHANGE: 21,
  GENERATE_BRACKETS_COMMAND: 22,
  GENERATE_CATEGORIES_COMMAND: 23,
  GENERATE_SCHEDULE_COMMAND: 24,
  PROPAGATE_COMPETITORS_COMMAND: 25,
  PUBLISH_COMPETITION_COMMAND: 26,
  REMOVE_ACADEMY_COMMAND: 27,
  REMOVE_COMPETITOR_COMMAND: 28,
  SAVE_ABSOLUTE_CATEGORY_COMMAND: 29,
  START_COMPETITION_COMMAND: 30,
  STOP_COMPETITION_COMMAND: 31,
  UNPUBLISH_COMPETITION_COMMAND: 32,
  UPDATE_ACADEMY_COMMAND: 33,
  UPDATE_COMPETITION_PROPERTIES_COMMAND: 34,
  UPDATE_COMPETITOR_COMMAND: 35,
  UPDATE_REGISTRATION_INFO_COMMAND: 36,
  UPDATE_STAGE_STATUS_COMMAND: 37
};

goog.object.extend(exports, proto.compservice.model.protobuf);
