backend:
  url: http://localhost:8089/

payment:
  service:
    url: http://localhost:8091/
  amount:
    rur: 100
  success:
    url: http://localhost:8080/callback
  fail:
    url: http://localhost:8080/callback

logging:
  config: classpath:log4j2.xml

keystore:
  password: compManagerPass
  alias: compManager

competition:
  service:
    url: http://localhost:8087/

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

mongodb:
  host: localhost
  auth:
    enabled: false
  username: compman
  password: compManagerPassword
  database:
    name: web
  admin:
   db: admin

